services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "krisinotedb"
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  spring-boot-app:
    image: stiliyandyankov/krisinotetest
    environment:
      SECRET_KEY: "5f3ae399bd393c4aacb06f3a564f86e99e0f5e6e22227b1c4a49ed0c73063d5f"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/krisinotedb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12345"
      SPRING_MAIL_USERNAME: "krisinote2301@gmail.com"
      SPRING_MAIL_PASSWORD: "oklpcbwsjpsunrch"
    ports:
      - "8081:8080"
    networks:
      - mysql
volumes:
  mysql:
networks:
  mysql: