app:
  jwt-secret-key:
    SECRET_KEY: ${SECRET_KEY}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    pool-size: 30
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
server:
  error:
    include-binding-errors: always
    include-message: always
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true